import { 
  LayoutDashboard, 
  UserCircle2, 
  Files, 
  Library, 
  Database, 
  Plus,
  Search,
  Bell,
  Maximize2,
  Video,
  Image as ImageIcon,
  Type,
  FolderOpen,
  MoreVertical,
  Clock,
  ExternalLink,
  MessageCircle,
  User,
  Download,
  Trash2,
  Mic,
  Send,
  ArrowLeft,
  ArrowRight,
  Instagram,
  Facebook,
  Youtube,
  Zap,
  Activity as LucideActivity,
  Volume2,
  VolumeX,
  Square,
  CreditCard,
  Mail,
  Lock,
  ChevronRight,
  PenLine,
  Eye,
  EyeOff,
  ShieldCheck,
  Loader2,
  Camera,
  CheckCircle,
  Check,
  Rocket,
  History,
  Monitor,
  Smartphone,
  Activity as LucideActivityIcon,
  ChevronDown as ArrowDown,
  Play,
  Pause,
  ChevronDown,
  Menu
} from "lucide-react";
import { CustomIcons } from "./custom-icons";

export const Icons = {
  Menu: Menu,
  CheckCircle: CheckCircle,
  Logo: CustomIcons.Logo,
  Dashboard: LayoutDashboard,
  CreativeStudio: CustomIcons.MagicWand,
  AIAgents: CustomIcons.AIAgents,
  MyProjects: CustomIcons.Folder,
  TemplatesLibrary: CustomIcons.Templates,
  AssetLibrary: CustomIcons.Gallery,
  Analytics: CustomIcons.Analytics,
  Settings: CustomIcons.Settings,
  Plus: Plus,
  Search: Search,
  Bell: Bell,
  Maximize: Maximize2,
  Video: CustomIcons.VideoIcon,
  Image: CustomIcons.ImageIcon,
  Text: CustomIcons.File,
  Database: Database,
  Library: Library,
  FolderOpen: FolderOpen,
  More: MoreVertical,
  Clock: Clock,
  ExternalLink: ExternalLink,
  MessageCircle: MessageCircle,
  User: User,
  MagicWand: CustomIcons.MagicWand,
  Download: Download,
  Trash: Trash2,
  Mic: CustomIcons.Mic,
  Send: Send,
  Success: CustomIcons.Success,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  Instagram: Instagram,
  Facebook: Facebook,
  Youtube: Youtube,
  Tiktok: CustomIcons.Tiktok,
  Activity: LucideActivityIcon,
  AudioWave: LucideActivity,
  whiteMagicWand: CustomIcons.whiteMagicWand,
  Volume: Volume2,
  Volume2: Volume2,
  Mute: VolumeX,
  Square: Square,
  CreditCard: CreditCard,
  Mail: Mail,
  Lock: Lock,
  ChevronRight: ChevronRight,
  PenLine: PenLine,
  Eye: Eye,
  EyeOff: EyeOff,
  Shield: ShieldCheck,
  Loader: Loader2,
  Camera: Camera,
  Rocket: Rocket,
  History: History,
  Monitor: Monitor,
  Smartphone: Smartphone,
  Files: Files,
  ArrowDown: ArrowDown,
  ChevronDown: ChevronDown,
  Check: Check,
  Play: Play,
  Pause: Pause
};
